[package]
name = "a-puzzle-a-day-solver"
version = "0.1.0"
authors = ["Keiichi Watanabe <udon.watanabe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
getopts = "0.2"
